CREATE OR REPLACE FORCE VIEW "LYNCHANIANO"."STOCKS" ("ID_COCESIONARIO", "NOMBRE_CONCESIONARIO", "CODCOCHE", "NOMBRE_COCHE", "STOCK") AS 
  select con.CIFC ID_COCESIONARIO,
con.NOMBRE NOMBRE_CONCESIONARIO,
coch.CODCOCHE,coch.NOMBRE NOMBRE_COCHE,
dist.CANTIDAD STOCK
from CONCESIONARIOS con,COCHES coch,DISTRIBUCION dist
where dist.CODCOCHE = coch.CODCOCHE and dist.CIFC = con.CIFC;
 

  CREATE OR REPLACE TRIGGER "LYNCHANIANO"."TRIGGERSTOCKS" 
INSTEAD OF INSERT OR DELETE OR UPDATE ON STOCKS 
declare
 
BEGIN
 
  if inserting then
   insert into DISTRIBUCION (CIFC,CODCOCHE,CANTIDAD)
   values (:new.ID_COCESIONARIO,:new.CODCOCHE,:new.STOCK);
   
   
  elsif deleting then
  
    delete from DISTRIBUCION
    where CODCOCHE=:old.CODCOCHE and CIFC =:old.ID_COCESIONARIO;
   
  else
  
    update DISTRIBUCION
    
    set CANTIDAD=:new.stock
    where CODCOCHE=:new.CODCOCHE and CIFC =:new.ID_COCESIONARIO;
    
   end if;
END;
/
ALTER TRIGGER "LYNCHANIANO"."TRIGGERSTOCKS" ENABLE;
 
