package Modelo;
// Generated 01-abr-2016 3:09:00 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Coches generated by hbm2java
 */
public class Coches implements java.io.Serializable {

	private String codcoche;
	private String nombre;
	private String modelo;
	private Set distribucions = new HashSet(0);

	public Coches() {
	}

	public Coches(String codcoche) {
		this.codcoche = codcoche;
	}

	public Coches(String codcoche, String nombre, String modelo, Set distribucions) {
		this.codcoche = codcoche;
		this.nombre = nombre;
		this.modelo = modelo;
		this.distribucions = distribucions;
	}

    public Coches(String codcoche, String nombre, String modelo) {
        this.codcoche = codcoche;
        this.nombre = nombre;
        this.modelo = modelo;
    }

        
	public String getCodcoche() {
		return this.codcoche;
	}

	public void setCodcoche(String codcoche) {
		this.codcoche = codcoche;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	public Set getDistribucions() {
		return this.distribucions;
	}

	public void setDistribucions(Set distribucions) {
		this.distribucions = distribucions;
	}

}
