package Modelo;
// Generated 01-abr-2016 3:09:00 by Hibernate Tools 3.4.0.CR1

/**
 * Distribucion generated by hbm2java
 */
public class Distribucion implements java.io.Serializable {

	private DistribucionId id;
	private Coches coches;
	private Concesionarios concesionarios;
	private Short cantidad;

	public Distribucion() {
	}

	public Distribucion(DistribucionId id, Coches coches, Concesionarios concesionarios) {
		this.id = id;
		this.coches = coches;
		this.concesionarios = concesionarios;
	}

	public Distribucion(DistribucionId id, Coches coches, Concesionarios concesionarios, Short cantidad) {
		this.id = id;
		this.coches = coches;
		this.concesionarios = concesionarios;
		this.cantidad = cantidad;
	}

	public DistribucionId getId() {
		return this.id;
	}

	public void setId(DistribucionId id) {
		this.id = id;
	}

	public Coches getCoches() {
		return this.coches;
	}

	public void setCoches(Coches coches) {
		this.coches = coches;
	}

	public Concesionarios getConcesionarios() {
		return this.concesionarios;
	}

	public void setConcesionarios(Concesionarios concesionarios) {
		this.concesionarios = concesionarios;
	}

	public Short getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Short cantidad) {
		this.cantidad = cantidad;
	}

}
