package Modelo;
// Generated 01-abr-2016 3:09:00 by Hibernate Tools 3.4.0.CR1

/**
 * StocksId generated by hbm2java
 */
public class StocksId implements java.io.Serializable {

	private String idCocesionario;
	private String nombreConcesionario;
	private String codcoche;
	private String nombreCoche;
	private Short stock;

	public StocksId() {
	}

	public StocksId(String idCocesionario, String codcoche) {
		this.idCocesionario = idCocesionario;
		this.codcoche = codcoche;
	}

	public StocksId(String idCocesionario, String nombreConcesionario, String codcoche, String nombreCoche,
			Short stock) {
		this.idCocesionario = idCocesionario;
		this.nombreConcesionario = nombreConcesionario;
		this.codcoche = codcoche;
		this.nombreCoche = nombreCoche;
		this.stock = stock;
	}

	public String getIdCocesionario() {
		return this.idCocesionario;
	}

	public void setIdCocesionario(String idCocesionario) {
		this.idCocesionario = idCocesionario;
	}

	public String getNombreConcesionario() {
		return this.nombreConcesionario;
	}

	public void setNombreConcesionario(String nombreConcesionario) {
		this.nombreConcesionario = nombreConcesionario;
	}

	public String getCodcoche() {
		return this.codcoche;
	}

	public void setCodcoche(String codcoche) {
		this.codcoche = codcoche;
	}

	public String getNombreCoche() {
		return this.nombreCoche;
	}

	public void setNombreCoche(String nombreCoche) {
		this.nombreCoche = nombreCoche;
	}

	public Short getStock() {
		return this.stock;
	}

	public void setStock(Short stock) {
		this.stock = stock;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StocksId))
			return false;
		StocksId castOther = (StocksId) other;

		return ((this.getIdCocesionario() == castOther.getIdCocesionario())
				|| (this.getIdCocesionario() != null && castOther.getIdCocesionario() != null
						&& this.getIdCocesionario().equals(castOther.getIdCocesionario())))
				&& ((this.getNombreConcesionario() == castOther.getNombreConcesionario())
						|| (this.getNombreConcesionario() != null && castOther.getNombreConcesionario() != null
								&& this.getNombreConcesionario().equals(castOther.getNombreConcesionario())))
				&& ((this.getCodcoche() == castOther.getCodcoche()) || (this.getCodcoche() != null
						&& castOther.getCodcoche() != null && this.getCodcoche().equals(castOther.getCodcoche())))
				&& ((this.getNombreCoche() == castOther.getNombreCoche())
						|| (this.getNombreCoche() != null && castOther.getNombreCoche() != null
								&& this.getNombreCoche().equals(castOther.getNombreCoche())))
				&& ((this.getStock() == castOther.getStock()) || (this.getStock() != null
						&& castOther.getStock() != null && this.getStock().equals(castOther.getStock())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdCocesionario() == null ? 0 : this.getIdCocesionario().hashCode());
		result = 37 * result + (getNombreConcesionario() == null ? 0 : this.getNombreConcesionario().hashCode());
		result = 37 * result + (getCodcoche() == null ? 0 : this.getCodcoche().hashCode());
		result = 37 * result + (getNombreCoche() == null ? 0 : this.getNombreCoche().hashCode());
		result = 37 * result + (getStock() == null ? 0 : this.getStock().hashCode());
		return result;
	}

}
