package Modelo;
// Generated 01-abr-2016 3:09:00 by Hibernate Tools 3.4.0.CR1

/**
 * Stocks generated by hbm2java
 */
public class Stocks implements java.io.Serializable {

	private StocksId id;

	public Stocks() {
	}

	public Stocks(StocksId id) {
		this.id = id;
	}

	public StocksId getId() {
		return this.id;
	}

	public void setId(StocksId id) {
		this.id = id;
	}

}
