/**************CREATE TABLAS Y OBETOS***************/



--LOS OBJETOS

CREATE TYPE TIPO_MUNICIPIO AS OBJECT (
    ID_Municipio  NUMBER(3),
    NOMBRE      VARCHAR(25),
    PROVINCIA   VARCHAR(25),
    SUPERFICIE  NUMBER(9)
);


CREATE TYPE TIPO_PERSONA AS OBJECT (
    ID_Persona NUMBER(3),
    NOMBRE      VARCHAR(25),
    APELLIDOS     VARCHAR(50),
    TELEFONO    NUMBER(9)
);

CREATE TYPE TIPO_HABITANTES AS TABLE OF TIPO_PERSONA;


CREATE TYPE TIPO_VIVIENDA AS OBJECT (
    ID_Vivienda  NUMBER(3),
    CALLE      VARCHAR(15),
    NUMERO    NUMBER(3),   
    MUNICIPIO        REF TIPO_MUNICIPIO,
    HABITANTES       TIPO_HABITANTES
);



--LAS TABLAS

CREATE TABLE TABLA_MUNICIPIO OF TIPO_MUNICIPIO(ID_Municipio primary key);
CREATE TABLE TABLA_VIVIENDAS OF TIPO_VIVIENDA(ID_Vivienda PRIMARY KEY) NESTED TABLE HABITANTES STORE AS LISTADO_VIVIENDAS;





/****************INSERTS****************/

-- INSERTO 4 VIVIENDAS
INSERT INTO TABLA_MUNICIPIO VALUES(001, 'MUNICIPIO1','PROVINCIA1', 1000);
INSERT INTO TABLA_MUNICIPIO VALUES(002, 'MUNICIPIO2','PROVINCIA2', 2000);
INSERT INTO TABLA_MUNICIPIO VALUES(003, 'MUNICIPIO3','PROVINCIA3', 3000);
INSERT INTO TABLA_MUNICIPIO VALUES(004, 'MUNICIPIO4','PROVINCIA4', 4000);




-- INSERTO VIVIENDAS CON SUS HABITANTES A LA TABLA MINI_PADRON 
INSERT INTO TABLA_VIVIENDAS
VALUES (1,'CALLE1', 1,  (SELECT REF(MUN) FROM TABLA_MUNICIPIO MUN WHERE MUN.ID_Municipio = 001), 
        TIPO_HABITANTES(TIPO_PERSONA(01, 'PERSONA1', 'APELLIDO', 645111111),
                              TIPO_PERSONA(02, 'PERSONA2', 'APELLIDO', 645222222)));
                              
INSERT INTO TABLA_VIVIENDAS
VALUES (2,'CALLE2', 2,   (SELECT REF(MUN) FROM TABLA_MUNICIPIO MUN WHERE MUN.ID_Municipio = 002), 
        TIPO_HABITANTES(TIPO_PERSONA(03, 'PERSONA3', 'APELLIDO', 645333333),
                              TIPO_PERSONA(04, 'PERSONA4', 'APELLIDO', 645444444),
                              TIPO_PERSONA(05, 'PERSONA5', 'APELLIDO', 645555555)));
                              
INSERT INTO TABLA_VIVIENDAS
VALUES (3,'CALLE3', 3,   (SELECT REF(MUN) FROM TABLA_MUNICIPIO MUN WHERE MUN.ID_Municipio = 003), 
        TIPO_HABITANTES(TIPO_PERSONA(06, 'PERSONA6', 'APELLIDO', 645666666),
                              TIPO_PERSONA(07, 'PERSONA7', 'APELLIDO', 645777777),
                              TIPO_PERSONA(08, 'PERSONA8', 'APELLIDO', 645888888)));
                              
INSERT INTO TABLA_VIVIENDAS
VALUES (4,'CALLE4', 4,   (SELECT REF(MUN) FROM TABLA_MUNICIPIO MUN WHERE MUN.ID_Municipio = 004), 
        TIPO_HABITANTES(TIPO_PERSONA(09, 'PERSONA9', 'APELLIDO', 645999999)));
        
        










/************************ SELECTS, UPDATES Y DELETES PARA PRUEBAS ***************************/


/***SELECTS***/

--MUESTRA TODO EL CONTENIDO DE LA TABLA_MUNICIPIO
SELECT * 
FROM TABLA_MUNICIPIO;

--MUESTRA: ID_Vivienda, CALLE, Y NOMBRE MUNICIPIO, NOMBRE PROVINCIA (TABLA_VIVIENDAS)
SELECT VIV.ID_Vivienda AS "ID_VIV", VIV.CALLE AS "Calle" , VIV.MUNICIPIO.NOMBRE AS "Municipio", VIV.MUNICIPIO.PROVINCIA AS "Provincia"
FROM TABLA_VIVIENDAS VIV;
	  
-- MUESTRA UNA POR UNA TODAS LAS VIVIENDAS(ID_Vivienda y CALLE)  CON TODOS SUS HABITANTES (TABLA_VIVIENDAS)
SELECT VIV.ID_Vivienda AS "ID ID_VIV", VIV.CALLE AS "Calle", cursor(select HAB.* from table(VIV.HABITANTES) HAB) AS HABITANTES
FROM TABLA_VIVIENDAS VIV;


/***INSERT***/

-- INSERTA UN HABITANTE (PERSONA) EN TABLA_VIVIENDAS
INSERT INTO TABLE(SELECT HABITANTES FROM TABLA_VIVIENDAS WHERE ID_Vivienda = 4)
VALUES (TIPO_PERSONA(23, 'PERSONA23', 'APELLIDO', 645232323));


/***UPDATE***/

-- MODIFICA EL NOMBRE DE UN HABITANTE DE LA TABLA_VIVIENDAS
UPDATE TABLE (SELECT HABITANTES FROM TABLA_VIVIENDAS WHERE ID_Vivienda = 4) modifica
SET VALUE(modifica) = TIPO_PERSONA(09, 'PERSONA_UPDATE', 'APELLIDO', 645999999)
WHERE VALUE(modifica) = TIPO_PERSONA(09, 'PERSONA9', 'APELLIDO', 645999999);

/***DELETES***/

-- BORRA UN HABITANTE DE LA TABLA_VIVIENDAS
DELETE FROM TABLE (SELECT HABITANTES FROM TABLA_VIVIENDAS WHERE ID_Vivienda = 4) elimina
WHERE VALUE(elimina) = TIPO_PERSONA(09, 'PERSONA_UPDATE', 'APELLIDO', 645999999);

-- BORRA UN REGISTRO (OBJETO: TIPO_VIVIENDAS) DE LA TABLA_VIVIENDAS
delete from TABLA_VIVIENDAS where ID_Vivienda = 4;













/************************* PROCEDIMIENTOS **************************/




/*ESTE PROCEDURE MUESTRA EL MUNICIPIO, PROVINCIA Y TODOS LOS HABITANTES DE LA VIVIENDA DE LA QUE INTRODUZCAMOS EL ID_Vivienda*/
CREATE OR REPLACE PROCEDURE CONSULTA_VIVIENDA (ID_VIVIEN NUMBER) AS 
    
    ID_Vivienda  NUMBER(3);
    CALLE      VARCHAR(15);
    NUMERO    NUMBER(3);
    NOMBRE      VARCHAR(15);
    PROVINCIA   VARCHAR(15);
CURSOR CURSOR1 IS 
    SELECT ID_Persona, NOMBRE, APELLIDOS, TELEFONO
    FROM THE (SELECT VIVS.HABITANTES
              FROM TABLA_VIVIENDAS VIVS
              WHERE ID_Vivienda = ID_VIVIEN);
    VAR_CURSOR CURSOR1%ROWTYPE;
BEGIN

SELECT  VIV.ID_Vivienda, VIV.CALLE, VIV.NUMERO, DEREF(MUNICIPIO).NOMBRE, DEREF(MUNICIPIO).PROVINCIA
    INTO  ID_Vivienda, CALLE, NUMERO, NOMBRE, PROVINCIA
    FROM TABLA_VIVIENDAS VIV
    WHERE VIV.ID_Vivienda = ID_VIVIEN;
    DBMS_OUTPUT.PUT_LINE('***********************************************************************************************************');
    DBMS_OUTPUT.PUT_LINE('***********************************************************************************************************');
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('       ID_VIVIENDA: '||ID_Vivienda||' =>  CALLE: '|| CALLE ||' =>  NÚMERO: '|| NUMERO);
    DBMS_OUTPUT.PUT_LINE('       MUNICIPIO: '||NOMBRE||' =>  PROVINCIA: '|| PROVINCIA);
    DBMS_OUTPUT.PUT_LINE('       --------');
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('                  HABITANTES:');
    DBMS_OUTPUT.PUT_LINE('                  ----------');
    OPEN CURSOR1;
        FETCH CURSOR1 INTO VAR_CURSOR;
        WHILE CURSOR1%FOUND LOOP
            DBMS_OUTPUT.PUT_LINE('                          ID: '||VAR_CURSOR.ID_Persona||' => NOMBRE: '||VAR_CURSOR.NOMBRE||' => APELLIDOS: '||VAR_CURSOR.APELLIDOS||' => NUM TELÉFONO: '||VAR_CURSOR.TELEFONO);
            FETCH CURSOR1 INTO VAR_CURSOR;
        END LOOP;
    CLOSE CURSOR1;
    DBMS_OUTPUT.PUT_LINE('-###########################################################################################################');
END CONSULTA_VIVIENDA;




--PROBAR CONSULTA_VIVIENDA()

SET SERVEROUTPUT ON;


DECLARE
  ID NUMBER;
BEGIN
  ID := &ID;

  CONSULTA_VIVIENDA(
    ID => ID
  );
rollback; 
END;






/*ESTE PROCEDURE MUESTRA TODOS LOS HABITANTES  EXISTENTES EN CADA UNA DE LAS VIVIENDAS*/
CREATE OR REPLACE PROCEDURE VIVIENDAS_SELECT AS 
    ID_VIVIEN NUMBER(3);

CURSOR CURSOR1 IS SELECT ID_Vivienda, CALLE, NUMERO, DEREF(MUNICIPIO).NOMBRE AS NOMBRE_MUNICIPIO, DEREF(MUNICIPIO).PROVINCIA AS PROVINCIA,DEREF(MUNICIPIO).SUPERFICIE AS SUPERFICIE
             FROM TABLA_VIVIENDAS ;


             
CURSOR CURSOR3 IS SELECT ID_Persona, NOMBRE, APELLIDOS, TELEFONO  
             FROM THE (SELECT VIVS.HABITANTES 
                       FROM TABLA_VIVIENDAS VIVS 
                       WHERE ID_Vivienda = ID_VIVIEN);

BEGIN
FOR VIV IN CURSOR1 LOOP
        DBMS_OUTPUT.PUT_LINE('***********************************************************************************************************');
        DBMS_OUTPUT.PUT_LINE('***********************************************************************************************************');
        DBMS_OUTPUT.PUT_LINE('   ID_VIVIENDA: '||VIV.ID_Vivienda||' =>  CALLE: '||VIV.CALLE||' =>  NÚMERO: '||VIV.NUMERO||' =>  MUNICIPIO: '||VIV.NOMBRE_MUNICIPIO||' =>  PROVINCIA: '||VIV.PROVINCIA||' => SUPERFICIE: '||VIV.SUPERFICIE);
        ID_VIVIEN:= VIV.ID_Vivienda;

        DBMS_OUTPUT.PUT_LINE('');
        DBMS_OUTPUT.PUT_LINE('              HABITANTES:');
        FOR ID_VIVIEN IN CURSOR3 LOOP
            DBMS_OUTPUT.PUT_LINE('                    ID_VIVIENDA: '||ID_VIVIEN.ID_Persona||' =>  NOMBRE: '||ID_VIVIEN.NOMBRE||' =>  APELLIDOS: '||ID_VIVIEN.APELLIDOS||' => NUM TELÉFONO: '||ID_VIVIEN.TELEFONO);
        END LOOP;
        DBMS_OUTPUT.PUT_LINE('***********************************************************************************************************');
        DBMS_OUTPUT.PUT_LINE('***********************************************************************************************************');
    END LOOP;
END VIVIENDAS_SELECT;




--PRUEBA VIVIENDAS_SELECT()

SET SERVEROUTPUT ON;


BEGIN
  VIVIENDAS_SELECT();
rollback; 
END;